apiVersion: v1
kind: Service
metadata:
  name: svc-portal-noticias
spec:
  type: NodePort
  ports:
    - port: 80 # service port is equal to the pod port dont need to specify targetPort
      # targetPort: 80
      nodePort: 30000
  selector:
    app: portal-noticias